export const Route = {
  ROOT: '/',
  DATA_PROCESS: '/dc/p/:id',
  API_ROOT: '/api/*',
  API_POST_PAYLOAD: '/api/payload',
  API_GET_PAYLOAD: '/api/payload:id',
  JOURNEY_DISPLAY_FLAGS: '/journey/flags/display/:id',
  INFO: '/info',
  OVERVIEW: '/home/overview',
  INTRO: '/home/intro',
  REVIEW: '/review',
  POST_REVIEW: '/review',
  SET_INACTIVE: '/review/set-inactive',
  SET_REQUESTED: '/review/set-requested',
  DEMO: '/demo',
  START_DEMO: '/start-demo',
  COOKIES: '/home/cookies',
  PRIVACY_POLICY: '/home/privacy-policy',
  TERMS_AND_CONDITIONS: '/home/terms-and-conditions',
  ACCESSIBILITY_STATEMENT: '/home/accessibility-statement',
  BACK: '/back',
} as const;
